{
 "title": "Request-Log",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "type", "label": "类型", "query": "HTTP : 1, RCP : 2, DNS : 3" },
   { "name": "flow", "label": "流向", "query": "IN : 0, OUT : 1" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n    bucket: \"ebpf\",\n    tag: \"namespace\",\n    predicate: (r) => true,\n)"
   },
   {
    "name": "podname",
    "label": "podname",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n    bucket: \"ebpf\",\n    tag: \"podname\",\n    predicate: (r) => r.namespace =~ /$namespace$/,\n)"
   },
   {
    "name": "nodename",
    "label": "nodename",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n    bucket: \"ebpf\",\n    tag: \"nodename\",\n    predicate: (r) => true,\n)"
   },
   {
    "name": "servicename",
    "label": "servicename",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n    bucket: \"ebpf\",\n    tag: \"servicename\",\n    predicate: (r) => r.namespace =~ /$namespace$/,\n)"
   },
   { "name": "url", "label": "URL" }
  ]
 },
 "panels": [
  {
   "title": "Request (n/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ebpf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"red\" and r._field == \"qps\" and r.nodename == \"cn-hangzhou.172.16.174.45\" and r.podname =~ /${podname}$/ and r.nodename =~ /${nodename}$/ and r.servicename =~ /${servicename}$/ and r.namespace =~ /${namespace}$/\n  ) \n  |> map(fn: (r) => ({r with\n      podname: r.podname,\n      namespace: r.namespace,\n      nodename: r.nodename,\n      servicename: r.servicename,\n      qps: r._value,\n      ts: r._time,\n    })\n  )\n  |> keep(columns: [\"qps\", \"ts\", \"podname\", \"namespace\", \"servicename\", \"nodename\"])\n  |> yield()"
    }
   ]
  },
  {
   "title": "ErrorRate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ebpf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"red\" and r._field == \"errrate\" and r.nodename == \"cn-hangzhou.172.16.174.45\" and r.podname =~ /${podname}$/ and r.nodename =~ /${nodename}$/ and r.servicename =~ /${servicename}$/ and r.namespace =~ /${namespace}$/\n  ) \n  |> map(fn: (r) => ({r with\n      podname: r.podname,\n      namespace: r.namespace,\n      nodename: r.nodename,\n      servicename: r.servicename,\n      errrate: r._value, \n      ts: r._time,\n    })\n  )\n  |> keep(columns: [\"errrate\", \"ts\", \"podname\", \"namespace\", \"servicename\", \"nodename\"])\n  |> yield()"
    }
   ]
  },
  {
   "title": "Duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ebpf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"red\" and r._field == \"duration\" and r.nodename == \"cn-hangzhou.172.16.174.45\" and r.podname =~ /${podname}$/ and r.nodename =~ /${nodename}$/ and r.servicename =~ /${servicename}$/ and r.namespace =~ /${namespace}$/\n  ) \n  |> map(fn: (r) => ({r with\n      podname: r.podname,\n      namespace: r.namespace,\n      nodename: r.nodename,\n      servicename: r.servicename,\n      duration: r._value,\n      ts: r._time,\n    })\n  )\n  |> keep(columns: [\"duration\", \"ts\", \"podname\", \"namespace\", \"servicename\", \"nodename\"])\n  |> yield()"
    }
   ]
  },
  {
   "title": "Request Log",
   "type": "table",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"ebpf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"traffic\" and r.nodename == \"cn-hangzhou.172.16.174.45\" and r.flow =~ /${flow}$/ and r.url =~ /${url}.*$/ and r.podname =~ /${podname}$/ and r.nodename =~ /${nodename}$/ and r.servicename =~ /${servicename}$/ and r.namespace =~ /${namespace}$/\n  ) \n  |> map(fn: (r) => ({r with\n      duration: r._value,\n      nodename: r.nodename,\n      podname: r.podname,\n      namespace: r.namespace,\n      ts: r._time,\n      code: r.code,\n      url: r.url,\n      srcip: r.srcip,\n      srcport: r.srcport,\n      dstip: r.dstip,\n      dstport: r.dstport,\n      servicename: r.servicename,\n      type: r.type,\n      flow: r.flow,\n      method: r.method,\n\n    })\n  )\n  |> keep(columns: [\"duration\", \"nodename\", \"podname\", \"namespace\", \"ts\", \"code\", \"url\", \"srcport\", \"srcip\", \"dstip\", \"dstport\", \"servicename\", \"type\", \"flow\", \"method\"])\n  |> limit(n:10)\n  |> yield()"
    }
   ]
  }
 ]
}