apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: ${NAMESPACE}
data:
  grafana.ini: |
    [dashboards]
      default_home_dashboard_path = "/opt/kubebpf/dashboards/request-log.json"