apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kubebpf-influxdb
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1000Gi
  local:
    path: ${INFLUXDB_PV_PATH}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ${INFLUXDB_HOST}
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem